name: Check

on:
  pull_request_target:
    branches: [ main ]
    types: [ opened, synchronize, labeled ]
  merge_group:
    types: [ checks_requested ]

jobs:
  check:
    name: Check
    runs-on: windows-latest
    outputs:
      result: ${{ steps.pass.outputs.result }}
    steps:
    - id: is_organization_member
      run: >
        $response = (curl -L
        -w '%{http_code}'
        -H "Accept: application/vnd.github+json"
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
        -H "X-GitHub-Api-Version: 2022-11-28"
        https://api.github.com/orgs/savushkin-r-d/members/${{ github.event.sender.login }})
        
        echo "response=$response" >> $env:GITHUB_OUTPUT
      continue-on-error: true
      
    - id: pass
      if: >-
        (github.event.action == 'labeled' && github.event.label.name == 'safe to test') ||
        ((github.event.action == 'synchronize' || github.event.action == 'opened') && steps.is_organization_member.outputs.response == '204') ||
        github.event_name == 'merge_group'
      run: echo "result=success" >> $env:GITHUB_OUTPUT
      
  build:
    needs: check
    if: needs.check.outputs.result == 'success'
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        event-type: my-event
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}' 
    