name: SafeToTestLabel

on:
  pull_request_target:
    branches: [ main ]
    types: [ labeled ]

jobs:
  call-workflow-passing-data:
    if: (github.event.action == 'labeled' && github.event.label.name == 'safe to test')
    uses: ./.github/workflows/dotnet_build.yml@main
    with:
      config-path: .github/workflows/dotnet_build.yml
    secrets: inherit