name: SafeToTestLabel

on:
  pull_request:
    branches: [ main ]
    types: [ labeled ]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    if: (github.event.action == 'labeled' && github.event.label.name == 'safe to test')
    steps:
      run: echo safe to test